import 'package:hive/hive.dart';

part 'item.g.dart';
// This file will be generated by running 'flutter packages pub run build_runner build'

@HiveType(typeId: 1) // Ensure typeId is unique
class Item extends HiveObject {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final int price;

  @HiveField(2)
  final String brand; // New field for brand

  @HiveField(3)
  final String name; // This will store the name without the brand and HTML tags

  @HiveField(4)
  final String categoryName;

  @HiveField(5)
  final String image;

  @HiveField(6)
  final String itemStatus;

  Item({
    required this.id,
    required this.price,
    required this.brand, // Add brand to constructor
    required this.name,
    required this.categoryName,
    required this.image,
    required this.itemStatus,
  });

  // Factory constructor for creating a new Item object from a map.
  factory Item.fromJson(Map<String, dynamic> json) {
    // Remove HTML tags and extract brand
    String rawName = json['name'] as String;
    String cleanedName = rawName.replaceAll(RegExp(r'<[/]?b>'), '');
    String itemBrand = cleanedName.split(' ').first;
    String itemName = cleanedName.substring(itemBrand.length).trim();

    return Item(
      id: json['id'] as int,
      price: json['price'] as int,
      brand: itemBrand, // Set extracted brand
      name: itemName, // Set name without brand and HTML tags
      categoryName: json['categoryName'] as String,
      image: json['image'] as String,
      itemStatus: json['itemStatus'] as String,
    );
  }

  // Method for converting Item object to a map.
  Map<String, dynamic> toJson() => {
    'id': id,
    'price': price,
    'name': '$brand $name', // Combine brand and name for original format
    'categoryName': categoryName,
    'image': image,
    'itemStatus': itemStatus,
  };

  @override
  String toString() {
    return 'Item{'
        'id: $id, '
        'price: $price, '
        'brand: $brand, ' // Include brand in toString
        'name: $name, '
        'categoryName: $categoryName, '
        'image: $image, '
        'itemStatus: $itemStatus}';
  }
}
