import 'package:hive/hive.dart';

part 'item.g.dart';
// This file will be generated by running 'flutter packages pub run build_runner build'

@HiveType(typeId: 0) // Unique typeId ensures that Hive can find our class
class Item extends HiveObject {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final int price;

  @HiveField(2)
  final String name;

  @HiveField(3)
  final String categoryName;

  @HiveField(4)
  final String image;

  @HiveField(5)
  final String itemStatus;

  Item({
    required this.id,
    required this.price,
    required this.name,
    required this.categoryName,
    required this.image,
    required this.itemStatus,
  });

  // Factory constructor for creating a new Item object from a map.
  factory Item.fromJson(Map<String, dynamic> json) => Item(
    id: json['id'] as int,
    price: json['price'] as int,
    name: json['name'] as String,
    categoryName: json['categoryName'] as String,
    image: json['image'] as String,
    itemStatus: json['itemStatus'] as String,
  );

  // Method for converting Item object to a map.
  Map<String, dynamic> toJson() => {
    'id': id,
    'price': price,
    'name': name,
    'categoryName': categoryName,
    'image': image,
    'itemStatus': itemStatus,
  };
}
